FROM golang:1.23.5 AS build-stage

WORKDIR /selection

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/selection/ ./cmd
COPY api/proto/generated/cars/ ./api/proto/generated/cars
COPY api/proto/generated/selection/ ./api/proto/generated/selection/
COPY api/proto/generated/storage/ ./api/proto/generated/storage
COPY api/proto/generated/carsget/ ./api/proto/generated/carsget
COPY entities/ ./entities
COPY internal/selection/ ./internal/selection
COPY internal/shared/adapters/ ./internal/shared/adapters
COPY internal/shared/config/ ./internal/shared/config
COPY internal/shared/errors/ ./internal/shared/errors

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd

FROM alpine:latest

WORKDIR /selection

COPY --from=build-stage /selection/main .

COPY assets/ /assets/
COPY configs/selection.yaml /configs/
COPY internal/selection/web/ /internal/selection/web/ 
COPY internal/search/web/templates/survey.html /internal/search/web/templates/
COPY web/ /web/

EXPOSE 8082

CMD ["./main"]