FROM golang:1.23.5 AS build-stage

WORKDIR /storage

COPY go.mod go.sum ./
RUN go mod download

COPY api/proto/ ./api/proto

COPY cmd/services/storage_selection/ ./cmd
COPY cmd/services/storage/ ./cmd/services/storage

COPY entities/ ./entities
COPY internal/services/storage/ ./internal/services/storage
COPY internal/services/register.go internal/services/run.go ./internal/services/
COPY internal/shared/config/ ./internal/shared/config

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd

FROM alpine:latest

WORKDIR /storage

COPY --from=build-stage /storage/main .

COPY configs/services/storage_selection.yaml /configs/services/

EXPOSE 8083

CMD ["./main"]