FROM golang:1.23.5 AS build-stage

WORKDIR /carsget

COPY go.mod go.sum ./
RUN go mod download

COPY api/proto/ ./api/proto

COPY cmd/services/carsget/ ./cmd

COPY entities/ ./entities
COPY internal/services/carsget/ ./internal/services/carsget/
COPY internal/services/register.go internal/services/run.go ./internal/services/
COPY internal/shared/config/ ./internal/shared/config

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd

FROM alpine:latest

WORKDIR /carsget

COPY --from=build-stage /carsget/main .

COPY configs/services/carsget.yaml /configs/services/

EXPOSE 8087

CMD ["./main"]